{% set name = "rage" %}
{% set version = "0.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}
source:
  url: https://github.com/str4d/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fc4d2f095cd89f3159e40359b443d46564e817768915456976cb1853bc199551

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]

test:
  commands:
    - rage --help

about:
  home: https://github.com/str4d/rage
  license: MIT
  summary: rage
  license_family: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - fhoehle
