{% set name = "rage" %}
{% set version = "0.9.2" %}

package:
  name: {{ name }}
  version: {{ version }}
source:
  url: https://github.com/str4d/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3bd287372eb6226b246459c1b5c39ecdb36b3495d7af4d2bee93bb3aad9ccf65

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - cargo-bundle-licenses

test:
  commands:
    - rage --help

about:
  home: https://github.com/str4d/rage
  license: MIT
  summary: rage
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - fhoehle
