{% set name = "rage" %}
{% set version = "0.8.1" %}

package:
  name: {{ name }}
  version: {{ version }}
source:
  url: https://github.com/str4d/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f9f39c987d398163bb2e843e02b0008d86842cb30d70b4c1e3470d9a4b9de87d

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - cargo-bundle-licenses

test:
  commands:
    - rage --help

about:
  home: https://github.com/str4d/rage
  license: MIT
  summary: rage
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - fhoehle
