{% set name = "rage" %}
{% set version = "0.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}
source:
  url: https://github.com/str4d/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: aad525028966843e0d18f893221c5951955f6b84e5fab34dc1e7bbc52a519e2a

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]

test:
  commands:
    - rage --help

about:
  home: https://github.com/str4d/rage
  license: MIT
  summary: rage
  license_family: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - fhoehle
