{% set name = "rage" %}
{% set version = "0.9.1" %}

package:
  name: {{ name }}
  version: {{ version }}
source:
  url: https://github.com/str4d/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c3dbd44dbdcfa69808dbe4d291453b8187a2302593fde5e7a88e6affeaeb25bf

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - cargo-bundle-licenses

test:
  commands:
    - rage --help

about:
  home: https://github.com/str4d/rage
  license: MIT
  summary: rage
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - fhoehle
