{% set name = "rage" %}
{% set version = "0.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}
source:
  url: https://github.com/str4d/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8b2b9daada1ebf324050be565f284f96b1f5b72f896fb4d1772797dc11bc4400

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]

test:
  commands:
    - rage --help

about:
  home: https://github.com/str4d/rage
  license: MIT
  summary: rage
  license_family: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - fhoehle
