{% set name = "rage" %}
{% set version = "0.10.0" %}

package:
  name: {{ name }}
  version: {{ version }}
source:
  url: https://github.com/str4d/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 34c39c28f8032c144a43aea96e58159fe69526f5ff91cb813083530adcaa6ea4

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - cargo-bundle-licenses

test:
  commands:
    - rage --help

about:
  home: https://github.com/str4d/rage
  license: MIT OR APACHE-2.0
  summary: rage
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - fhoehle
    - pavelzw
