schema_version: 1

context:
  version: "0.12.1"

package:
  name: rage
  version: ${{ version }}

source:
  url: https://github.com/str4d/rage/archive/v${{ version }}.tar.gz
  sha256: 3684e7e269a677180db116cb8115b008ea462dbb6f223f6983dd6750a863afaa

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root "$PREFIX" --path rage
        else:
          - cargo auditable install --locked --no-track --bins --root %PREFIX% --path rage
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cargo-auditable
    - cargo-bundle-licenses

tests:
  - script:
      - rage --help
  - package_contents:
      bin:
        - rage
        - rage-keygen
      strict: true

about:
  license: MIT OR Apache-2.0
  summary: rage
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  homepage: https://github.com/str4d/rage
  repository: https://github.com/str4d/rage

extra:
  recipe-maintainers:
    - fhoehle
    - pavelzw
