schema_version: 1

context:
  name: rage
  version: 0.11.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/str4d/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: b00559285c9fa5779b2908726d7a952cbf7cb629008e4c4c23a5c137c98f3f09

build:
  number: 1
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root "$PREFIX" --path rage
        else:
          - cargo auditable install --locked --no-track --bins --root %PREFIX% --path rage
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cargo-auditable
    - cargo-bundle-licenses

tests:
  - script:
      - rage --help

about:
  license: MIT OR Apache-2.0
  summary: rage
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  homepage: https://github.com/str4d/rage

extra:
  recipe-maintainers:
    - fhoehle
    - pavelzw
